using Erp.Api.Core;
using Erp.Api.Data;
using Erp.Api.Dtos;
using Erp.Api.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Erp.Api.Controllers;

[ApiController]
[Authorize]
[Route("api/v1/sales/orders/{orderId:long}")]
public class SalesOrderPaymentsController(ErpDbContext db, RbacService rbac) : ControllerBase
{
    private const string Resource = "sales-orders";

    private static SoPaymentRequestOut ToDto(SoPaymentRequest r) => new(
        r.Id, r.OrderId, r.DueDate, r.Amount, r.AutoGenerated, r.Status);

    private static SoPaymentActualOut ToDto(SoPaymentActual a) => new(
        a.Id, a.OrderId, a.PayDate, a.Amount, a.MethodId, a.Note);

    private async Task<bool> Denied(string action) =>
        !await rbac.HasPermissionAsync(User, "DOCUMENT", Resource, action);

    private ObjectResult Forbidden(string action) =>
        StatusCode(403, new ApiError("WF_NO_PERMISSION", $"Thiếu quyền {action} trên DOCUMENT:{Resource}"));

    private async Task<SalesOrder?> FindOrder(long orderId) =>
        await db.SalesOrders.FirstOrDefaultAsync(x => x.Id == orderId);

    // ----- Payment requests (yêu cầu thanh toán) -----
    [HttpGet("payment-requests")]
    public async Task<IActionResult> ListRequests(long orderId)
    {
        if (await Denied("VIEW")) return Forbidden("VIEW");
        if (await FindOrder(orderId) is null)
            return NotFound(new ApiError("NOT_FOUND", $"Đơn hàng {orderId} không tồn tại"));
        var items = await db.SoPaymentRequests.AsNoTracking().Where(x => x.OrderId == orderId)
            .OrderBy(x => x.Id).ToListAsync();
        return Ok(items.Select(ToDto).ToList());
    }

    [HttpPost("payment-requests")]
    public async Task<IActionResult> CreateRequest(long orderId, [FromBody] SoPaymentRequestIn body)
    {
        if (await Denied("UPDATE")) return Forbidden("UPDATE");
        if (await FindOrder(orderId) is null)
            return NotFound(new ApiError("NOT_FOUND", $"Đơn hàng {orderId} không tồn tại"));
        var req = new SoPaymentRequest
        {
            OrderId = orderId, DueDate = body.DueDate, Amount = body.Amount,
            Status = body.Status, AutoGenerated = false,
        };
        db.SoPaymentRequests.Add(req);
        await db.SaveChangesAsync();
        return StatusCode(201, ToDto(req));
    }

    [HttpPut("payment-requests/{reqId:long}")]
    public async Task<IActionResult> UpdateRequest(long orderId, long reqId, [FromBody] SoPaymentRequestUpdate body)
    {
        if (await Denied("UPDATE")) return Forbidden("UPDATE");
        var req = await db.SoPaymentRequests.FirstOrDefaultAsync(x => x.Id == reqId && x.OrderId == orderId);
        if (req is null) return NotFound(new ApiError("NOT_FOUND", "Yêu cầu thanh toán không tồn tại"));
        Mapper.Apply(body, req, skipNulls: true);
        await db.SaveChangesAsync();
        return Ok(ToDto(req));
    }

    [HttpDelete("payment-requests/{reqId:long}")]
    public async Task<IActionResult> DeleteRequest(long orderId, long reqId)
    {
        if (await Denied("UPDATE")) return Forbidden("UPDATE");
        var req = await db.SoPaymentRequests.FirstOrDefaultAsync(x => x.Id == reqId && x.OrderId == orderId);
        if (req is null) return NotFound(new ApiError("NOT_FOUND", "Yêu cầu thanh toán không tồn tại"));
        db.SoPaymentRequests.Remove(req);
        await db.SaveChangesAsync();
        return NoContent();
    }

    // ----- Payment actuals (thực tế thanh toán) -----
    [HttpGet("payment-actuals")]
    public async Task<IActionResult> ListActuals(long orderId)
    {
        if (await Denied("VIEW")) return Forbidden("VIEW");
        if (await FindOrder(orderId) is null)
            return NotFound(new ApiError("NOT_FOUND", $"Đơn hàng {orderId} không tồn tại"));
        var items = await db.SoPaymentActuals.AsNoTracking().Where(x => x.OrderId == orderId)
            .OrderBy(x => x.Id).ToListAsync();
        return Ok(items.Select(ToDto).ToList());
    }

    [HttpPost("payment-actuals")]
    public async Task<IActionResult> CreateActual(long orderId, [FromBody] SoPaymentActualIn body)
    {
        if (await Denied("UPDATE")) return Forbidden("UPDATE");
        if (await FindOrder(orderId) is null)
            return NotFound(new ApiError("NOT_FOUND", $"Đơn hàng {orderId} không tồn tại"));
        var actual = new SoPaymentActual
        {
            OrderId = orderId, PayDate = body.PayDate, Amount = body.Amount,
            MethodId = body.MethodId, Note = body.Note,
        };
        db.SoPaymentActuals.Add(actual);
        await db.SaveChangesAsync();
        return StatusCode(201, ToDto(actual));
    }

    [HttpPut("payment-actuals/{actualId:long}")]
    public async Task<IActionResult> UpdateActual(long orderId, long actualId, [FromBody] SoPaymentActualUpdate body)
    {
        if (await Denied("UPDATE")) return Forbidden("UPDATE");
        var actual = await db.SoPaymentActuals.FirstOrDefaultAsync(x => x.Id == actualId && x.OrderId == orderId);
        if (actual is null) return NotFound(new ApiError("NOT_FOUND", "Thực tế thanh toán không tồn tại"));
        Mapper.Apply(body, actual, skipNulls: true);
        await db.SaveChangesAsync();
        return Ok(ToDto(actual));
    }

    [HttpDelete("payment-actuals/{actualId:long}")]
    public async Task<IActionResult> DeleteActual(long orderId, long actualId)
    {
        if (await Denied("UPDATE")) return Forbidden("UPDATE");
        var actual = await db.SoPaymentActuals.FirstOrDefaultAsync(x => x.Id == actualId && x.OrderId == orderId);
        if (actual is null) return NotFound(new ApiError("NOT_FOUND", "Thực tế thanh toán không tồn tại"));
        db.SoPaymentActuals.Remove(actual);
        await db.SaveChangesAsync();
        return NoContent();
    }
}
